In [1]:
import numpy as np

In [2]:
a=np.floor(10*np.random.rand(2,5)) #rand=range in bw 0 and 1
print(a)

[[8. 4. 4. 0. 9.]
 [9. 7. 5. 8. 8.]]


In [4]:
b=np.arange(1,33).reshape(8,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [8]:
np.vsplit(b,4)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [9]:
np.hsplit(b,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21],
        [25],
        [29]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22],
        [26],
        [30]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23],
        [27],
        [31]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24],
        [28],
        [32]])]

In [10]:
np.vsplit(b,(3,5))#split after 3th row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [17]:
#create an array with 4 rows and 8 coloums
a=np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [24]:
np.hsplit(a,(3,7))

[array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19],
        [21, 22, 23],
        [25, 26, 27],
        [29, 30, 31]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24],
        [28],
        [32]]),
 array([], shape=(8, 0), dtype=int64)]

#trigonometry

In [28]:
np.pi

3.141592653589793

In [29]:
a=[np.pi/4,np.pi/3,np.pi/2,np.pi]# radians
print(a)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [32]:
b=np.rad2deg(a)#converts randians to degree
print(b)

[ 45.  60.  90. 180.]


In [34]:
np.deg2rad(b)#converts degree to radians

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [36]:
np.sin(a)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [38]:
b=[np.sin(0),np.sin(90)]
print(b)

[0.0, 0.8939966636005579]


In [46]:
st=np.array([2,3,3,4,5])
print(st)


[2 3 3 4 5]


In [43]:
np.mean(st)

3.5

In [44]:
np.median(st)

3.5

In [50]:
np.var(st)#variance=(std)^2

1.04

In [52]:
#standard deviation
m=np.std(st)     #σ= √(∑(x−¯x) ( x − x ¯ ) 2 /n)
print(m)

1.019803902718557


In [54]:
c=m*m
print(c)

1.04


In [60]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [61]:
np.linalg.inv(c)#a^-1

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
c=np.arange(2,6).reshape(2,2)
print(c)

[[2 3]
 [4 5]]


In [66]:
print(np.argmax(c))#maximun no index position inthe matrix form

3


In [67]:
print(np.argmax(c,axis=1))#biggest no in matrix c and print the constant base index positions# axis=0 refers to row # axis=1 refers to coloums

[1 1]


In [68]:
print(np.argmax(c,axis=0))

[1 1]


In [72]:
print(np.argmin(c,axis=0))

[0 0]


#searching

In [74]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [84]:
a=np.array([34,56,7,17,88,91])
for i in a:
  if(i%2==0):
    print(i)
  else:
    print("null")

34
56
null
null
88
null


In [87]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [94]:
a=np.array([6,2,8,2,10])
x=np.searchsorted(a,10)
print(x)

4


In [96]:
#sorting
a=np.array(["banana","pavani","apple"])
print(np.sort(a))

['apple' 'banana' 'pavani']


In [99]:
a=np.array([[1,2,34,4],[3,5,9,8]])
print(np.sort(a))

[[ 1  2  4 34]
 [ 3  5  8  9]]


In [102]:
#array filter
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]
print(arr[x])

[40 50 67 78]


In [106]:
a=np.array([40,43,50,44,67,78])
f=np.where(a%2==0)
print(f)

(array([0, 2, 3, 5]),)


In [104]:
a[f]

array([40, 50, 44, 78])

In [110]:
a=np.array(["pavani","sweety","kanteti"])
initial=np.array(["a","b","c"])
for i,j in zip(initial,a):
     print(i,".",j)

a . pavani
b . sweety
c . kanteti


In [114]:
a=np.array([1,2,3,4])
initial=np.array([9,8,7,6])
for i,j in zip(a,initial):
     print(i,".",j)

1 . 9
2 . 8
3 . 7
4 . 6


In [119]:
a=np.array([9,8,7,6])
b=np.array([1,2,3,4])
n=a+b
print(n)

[10 10 10 10]


In [121]:
a=np.array([9,8,7,6])
b=np.array([1,2,3,4])
n=np.multiply(a,b)
print(n)

[ 9 16 21 24]


In [122]:
a=np.array([9,8,7,6])
b=np.array([1,2,3,4])
n=np.divide(a,b)
print(n)

[9.         4.         2.33333333 1.5       ]


In [123]:
a=np.array([9,8,7,6])
b=np.array([1,2,3,4])
n=np.mod(a,b)
print(n)

[0 0 1 2]


In [125]:
a=np.array([9,8,7,6])
b=np.array([1,2,3,4])
n=np.divmod(a,b)
print(n)

(array([9, 4, 2, 1]), array([0, 0, 1, 2]))


#logarithms

In [131]:
a=np.arange(1,10)
print(a)


[1 2 3 4 5 6 7 8 9]


In [127]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [128]:
print(np.log2(a))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [132]:
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [133]:
a=np.array([10,15,3])
x=np.cumprod(a)
print(x)

[ 10 150 450]


In [134]:
a=np.array([10,15,3])
x=np.cumsum(a)
print(x)

[10 25 28]


In [138]:
a=np.array([10,15,3])
print(np.diff(a))

[  5 -12]


In [140]:
a=6
b=2
print(np.lcm(a,b))

6


In [146]:
a=6
b=2
print(np.gcd(a,b))

2


In [151]:
a=np.array([12,15,60])
d=np.lcm.reduce(a)
print(d)

60
