In [ ]:
#importing
import numpy as np

#arrays

In [ ]:
#creating 1d arrays
a = np.array([2,3,4,5])
print(type(a))


<class 'numpy.ndarray'>


In [ ]:
#creating 2d array rows and coloums
b=np.array([[1,2,3,4],[6,7,8,9]])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
#creating 3d array row,cloums,groups
c=np.array([[[1,2,3],[5,6,7]],[[9,7,1],[0,7,5]]])
print(c)

[[[1 2 3]
  [5 6 7]]

 [[9 7 1]
  [0 7 5]]]


In [ ]:
#checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
#ones,zeros-groups,rows,coloums 1d,2d,3d
d=np.zeros((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d=np.eye((3,4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
r=np.eye(4,3)
print(r)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#arrange
h=np.arange(5,1001,5)
print(h)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
v=np.linspace(12,24,12)
print(v)

[12.         13.09090909 14.18181818 15.27272727 16.36363636 17.45454545
 18.54545455 19.63636364 20.72727273 21.81818182 22.90909091 24.        ]


In [ ]:
l=np.arange(1,7).reshape(2,3)
print(l)



[[1 2 3]
 [4 5 6]]


In [ ]:
print(l+l)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
r=np.arange(8,14).reshape(2,3)
print(r)


[[ 8  9 10]
 [11 12 13]]


In [ ]:
g=np.sum((l,r),axis=1)
print(g)

[[ 5  7  9]
 [19 21 23]]


In [ ]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a*b)

[[2 0]
 [0 4]]


In [ ]:
b=np.array([25,289,361,81])#find the square root and iterate throught result values :5 and sqrt=25
for i in b :

  print(np.sqrt(i),"sqrt is",i)

5.0 sqrt is 25
17.0 sqrt is 289
19.0 sqrt is 361
9.0 sqrt is 81


In [ ]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5) #no.of groups=2->2 coloumsin each group
print(a)                        #NO OF ROWS =3->3 GROUPS ARE FORMED
print("OUTPUT OF STACK")
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
OUTPUT OF STACK
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a=10*np.random.rand(2,5) #rand=range in bw 0 and 1
print(a)

NameError: name 'np' is not defined